spring.application.name=CAA_SP

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/caa_db
spring.datasource.username=postgres
spring.datasource.password=caa_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080